services:
  yt-auto-recorder:
    build: .
    container_name: yt-auto-recorder
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      CHANNEL_LIST: /config/recording-channels.txt
      SETTINGS_FILE: /config/settings.json
      BASE_DIR: /recordings
      CHECK_INTERVAL: 30
      FINALIZE_MODE: remux
      YTDLP_FORMAT: "bestvideo[vcodec^=avc1]+bestaudio[acodec^=mp4a]/best[vcodec^=avc1][acodec^=mp4a]/best"
      VIDEO_CRF: 23
      VIDEO_PRESET: veryfast
      AUDIO_BITRATE: 192k
    volumes:
      - ./data/config:/config
      - ./data/recordings:/recordings
